import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import Hero from "@/app/components/Hero_Section";
import Banner from "@/app/components/Banner";
import Vision_Section from "@/app/components/Visoion_Section";
import PopularServices from "./components/Popular_Service";
import Plane from "@/app/components/Plane";
import Footer from "./components/Footer";
import Contact from "./components/Contact";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased bg-black text-white">
        <Header />
        <main className="flex flex-col items-center justify-center min-h-screen">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
